# Generated by Django 5.0.2 on 2024-02-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anything', '0005_rename_exact_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_quantity',
            new_name='product_number',
        ),
    ]
